version: '3'
services:
  app:
    hostname: app-server
    build: ./app
    volumes: 
      - ./app:/app
      - socket:/tmp
    container_name: 'app-server'
    ports:
      - '5000:5000'
    networks:
      - linebot-network
    command: uwsgi --ini /app/uwsgi.ini

  web:
    image: nginx:latest
    ports:
      - "80:80"
    container_name: 'linebot-nginx'
    volumes:
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
      - socket:/tmp
    networks:
      - linebot-network

  mysql-db:
    container_name: "mysql-db"
    image: mysql:5.7
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - db_volume:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    environment: # Set up mysql database name and password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: linebot
      MYSQL_USER: kota1110
      MYSQL_PASSWORD: Kota0108
    ports:
      - 3306:3306
    networks:
      - linebot-network

networks:
  linebot-network:
    driver: bridge

volumes:
  socket:
  db_volume:
